export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const LOAD_INGREDIENTS_FAILED = 'LOAD_INGREDIENTS_FAILED'
