export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const LOAD_INGREDIENTS_FAILED = 'LOAD_INGREDIENTS_FAILED'

export const BURGER_ORDER_START = 'BURGER_ORDER_START'
export const BURGER_ORDER_FAILED = 'BURGER_ORDER_FAILED'
export const BURGER_ORDER_SUCCESS = 'BURGER_ORDER_SUCESS'
export const ORDER_REDIRECT = 'ORDER_REDIRECT'